name: Maven Package

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      build-parameters:
        description: Build parameters of Maven
        default: -B test --file pom.xml
        type: string
        required: false
  #scheduling the cron job for every 10 mins
  #schedule:
  #  - cron: "*/10 * * * *"

concurrency: 
# concurrency if the same workflow runs at the same time within a group, if cancel in progress is true 
#if true, it will cancel the in-progress workflow and then run the new workflow
#else the new workflow will wait until the in-progress workflow completes
  group: sample-dep
  cancel-in-progress: true 

jobs:
  build:
    name: Build-Maven
    runs-on: ubuntu-latest

    env:
      buildParam: ${{ github.event_name == 'workflow_dispatch' && inputs.build-parameters || '-B test --file pom.xml' }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build code using Maven command
        run: |
            echo "Sample ${{ env.buildParam }}" >> sample.txt
      - name: upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: download-file
          path: sample.txt
  getSampleFile:
    name: Get Sample file
    # this job needs to be completed within 1 min and throw an error if it takes more than 1 min
    timeout-minutes: 1 
    needs: ["build"]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        level: ["hello"]
        include:
          - os: ubuntu-20.04
          - level: "Hello all"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v7
        with:
          name: download-file
      - name: Read the downloaded file
        run: |
            cat sample.txt | grep -i "test"
            echo ${{ matrix.level }}
